# ---------------------------------------------------------------------------- #
#                                Default profile                               #
# ---------------------------------------------------------------------------- #

# --------------------------------- Compiler --------------------------------- #

[profile.default]
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 20_000
libs = ["dependencies"]
auto_detect_remappings = false
invariant = { fail_on_revert = true }

# -------------------------------- Remappings -------------------------------- #

remappings = [
    "forge-std=dependencies/forge-std-1.9.2/src",
    "@uniswap/universal-router=dependencies/@uniswap-universal-router-1.6.0",
    "usdn-contracts=dependencies/@smardex-usdn-contracts-0.22.0",
    "permit2=dependencies/@uniswap-permit2-1.0.0",
    "@chainlink/=dependencies/@chainlink-1.2.0/",
    "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.0.2/",
    "openzeppelin-contracts/=dependencies/openzeppelin-contracts-4.7.0/",
    "@uniswap/v2-core=dependencies/@uniswap-v2-core-1.0.1",
    "solmate=dependencies/solmate-6.7.0",
    "solady=dependencies/solady-0.0.228",
    "@uniswap/v3-core=dependencies/@uniswap-v3-core-1.0.2-solc-0.8-simulate",
    "openzeppelin-foundry-upgrades/=dependencies/openzeppelin-foundry-upgrades-0.3.1/src/",
    "solidity-stringutils=dependencies/openzeppelin-foundry-upgrades-0.3.1/lib/solidity-stringutils",
    "@pythnetwork/pyth-sdk-solidity/=dependencies/@pythnetwork-pyth-sdk-solidity-3.1.0/",
    "@openzeppelin/contracts-upgradeable/=dependencies/@openzeppelin-contracts-upgradeable-5.0.2/",
]

# ---------------------------------- Format ---------------------------------- #

[profile.default.fmt]
line_length = 120
bracket_spacing = true
wrap_comments = true
number_underscore = "thousands"

# ---------------------------------------------------------------------------- #
#                                 Local profile                                #
# ---------------------------------------------------------------------------- #

[profile.local]
ffi = true

# ---------------------------------- Fuzzing --------------------------------- #

[profile.local.fuzz]
runs = 10_000

[profile.local.invariant]
runs = 10_000
depth = 15
# call_override = true # makes invariant tests hang
dictionary_weight = 80

# ---------------------------------------------------------------------------- #
#                             Heavy fuzzing profile                            #
# ---------------------------------------------------------------------------- #

[profile.heavy_fuzzing]
ffi = true

# ---------------------------------- Fuzzing --------------------------------- #

[profile.heavy_fuzzing.fuzz]
runs = 1_000_000

[profile.heavy_fuzzing.invariant]
runs = 1_000_000
depth = 30
# call_override = true
dictionary_weight = 80

# ---------------------------------------------------------------------------- #
#                                  CI profile                                  #
# ---------------------------------------------------------------------------- #

[profile.ci]
verbosity = 3

# ---------------------------------- Fuzzing --------------------------------- #

[profile.ci.fuzz]
runs = 256

[profile.ci.invariant]
runs = 256
depth = 5
# call_override = false
dictionary_weight = 40

# ---------------------------------------------------------------------------- #
#                              Complete CI profile                             #
# ---------------------------------------------------------------------------- #

[profile.heavy_ci]
verbosity = 3
ffi = true

# ---------------------------------- Fuzzing --------------------------------- #

[profile.heavy_ci.fuzz]
runs = 1024

[profile.heavy_ci.invariant]
runs = 1024
depth = 10
dictionary_weight = 60

# ---------------------------------------------------------------------------- #
#                                  Deployments                                 #
# ---------------------------------------------------------------------------- #

[rpc_endpoints]
mainnet = "${URL_ETH_MAINNET}"
sepolia = "${URL_SEPOLIA}"
anvil = "${URL_ANVIL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }

[dependencies]
"@uniswap-universal-router" = "1.6.0"
forge-std = "1.9.2"
"@smardex-usdn-contracts" = { version = "0.22.0", git = "git@github.com:SmarDex-Ecosystem/usdn-contracts.git", rev = "2a49f7e710fe12bb3c4086e37c91abfb6fc87611" }
"@uniswap-permit2" = { version = "1.0.0", url = "https://github.com/Uniswap/permit2/archive/cc56ad0f3439c502c246fc5cfcc3db92bb8b7219.zip" }
"@chainlink" = { version = "1.2.0", url = "https://github.com/smartcontractkit/chainlink/archive/c3dc764bba9e1c57b3f7933bcb804a1740fab695.zip" }
"@openzeppelin-contracts" = "5.0.2"
"openzeppelin-contracts" = { version = "4.7.0", url = "https://github.com/OpenZeppelin/openzeppelin-contracts/archive/refs/tags/v4.7.0.zip" }
"@uniswap-v2-core" = "1.0.1"
solady = "0.0.228"
solmate = "6.7.0"
"@uniswap-v3-core" = "1.0.2-solc-0.8-simulate"
openzeppelin-foundry-upgrades = "0.3.1"
"@pythnetwork-pyth-sdk-solidity" = "3.1.0"
"@openzeppelin-contracts-upgradeable" = "5.0.2"

[soldeer]
# whether soldeer manages remappings
remappings_generate = false
