name: CI with heavy test run
on:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: heavy_ci
  URL_ETH_MAINNET: ${{ secrets.URL_ETH_MAINNET }}
  HERMES_RA2_NODE_URL: ${{ secrets.HERMES_RA2_NODE_URL }}

jobs:
  heavy-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: 'universal-router,usdn-contracts'

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ steps.app-token.outputs.token }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci && forge soldeer install

      - name: Build test_utils
        run: cargo build --release

      # - name: Check gas snapshots
      #   run: npm run snapshot:check

      - name: Run tests
        run: forge test
