name: Natspec report
on:
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  natspec-smells:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "universal-router,usdn-contracts"

      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ steps.app-token.outputs.token }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Add app token to git config for soldeer to use
        env:
          APP_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git config --global url."https://x-access-token:$APP_TOKEN@github.com/".insteadOf "git@github.com:"
      - name: Install deps
        run: npm ci && forge soldeer install

      - name: Report natspec smells findings
        uses: SmarDex-Ecosystem/natspec-smells-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./
          update-comment: true
